In [15]:
import pandas as pd
data=pd.read_csv("C:/Users/25160/Desktop/ginf.csv")
d1=data[(data["league"]=="D1")&(data["season"]==2012)]
d1 = d1.reset_index(drop=True)
l1=list(d1["ht"])+list(d1["at"])
l1=list(set(l1))
t1=dict(zip(l1,[0 for i in l1]))#进球数
s1=dict(zip(l1,[0 for i in l1]))#丢球数
r1=[]
r2=[]
for i in range(d1.shape[0]):
    t1[d1.loc[i]['ht']]+=int(d1.loc[i]['fthg'])
    t1[d1.loc[i]['at']]+=int(d1.loc[i]['ftag'])
    s1[d1.loc[i]['ht']]+=int(d1.loc[i]['ftag'])
    s1[d1.loc[i]['at']]+=int(d1.loc[i]['fthg'])
for i in range(len(t1)):
    r1.append([list(t1.items())[i][0],list(t1.items())[i][1]])
    r2.append([list(t1.items())[i][0],list(s1.items())[i][1]])
r1

[['Bayern Munich', 77],
 ['FC Cologne', 39],
 ['TSG Hoffenheim', 41],
 ['VfB Stuttgart', 63],
 ['VfL Wolfsburg', 47],
 ['Nurnberg', 38],
 ['Schalke 04', 74],
 ['SC Freiburg', 45],
 ['Mainz', 47],
 ['Borussia Dortmund', 80],
 ['FC Augsburg', 36],
 ['Borussia Monchengladbach', 49],
 ['Bayer Leverkusen', 52],
 ['Kaiserslautern', 24],
 ['Hamburg SV', 35],
 ['Hertha Berlin', 38],
 ['Hannover 96', 41],
 ['Werder Bremen', 49]]

In [16]:
r1=pd.DataFrame(r1)
r2=pd.DataFrame(r2)

In [17]:
r1.columns=['name','goal']
r2.columns=['name','lose']
r1.to_csv('C:/Users/25160/Desktop/3_1.csv', index=False)
r2.to_csv('C:/Users/25160/Desktop/3_2.csv', index=False)

In [20]:
r1

                        name  goal
0              Bayern Munich    77
1                 FC Cologne    39
2             TSG Hoffenheim    41
3              VfB Stuttgart    63
4              VfL Wolfsburg    47
5                   Nurnberg    38
6                 Schalke 04    74
7                SC Freiburg    45
8                      Mainz    47
9          Borussia Dortmund    80
10               FC Augsburg    36
11  Borussia Monchengladbach    49
12          Bayer Leverkusen    52
13            Kaiserslautern    24
14                Hamburg SV    35
15             Hertha Berlin    38
16               Hannover 96    41
17             Werder Bremen    49