In [37]:
import pandas as pd
data=pd.read_csv("C:/Users/25160/Desktop/ginf.csv")
d1=data[(data["league"]=="D1")&(data["season"]==2012)]
d1 = d1.reset_index(drop=True)
l1=list(d1["ht"])+list(d1["at"])
l1=list(set(l1))
a1=dict(zip(l1,[0 for i in l1]))#赢
b1=dict(zip(l1,[0 for i in l1]))#平
c1=dict(zip(l1,[0 for i in l1]))#败
r1=[]

In [38]:
for i in range(d1.shape[0]):
    if d1.loc[i]['fthg']>d1.loc[i]['ftag']:
        a1[d1.loc[i]['ht']]+=1
        c1[d1.loc[i]['at']]+=1
    elif d1.loc[i]['fthg']<d1.loc[i]['ftag']:
        a1[d1.loc[i]['at']]+=1
        c1[d1.loc[i]['ht']]+=1
    else:
        b1[d1.loc[i]['ht']]+=1
        b1[d1.loc[i]['at']]+=1
for i in range(len(a1)):
    r1.append([list(a1.items())[i][0],list(a1.items())[i][1],list(b1.items())[i][1],list(c1.items())[i][1]])
r1=pd.DataFrame(r1)
r1.columns=['name','a','b','c']
#r1.to_csv('C:/Users/25160/Desktop/2.csv', index=False)

                        name   a   b   c
0   Borussia Monchengladbach  17   9   8
1                 Schalke 04  20   4  10
2                 FC Cologne   8   6  20
3              Werder Bremen  11   9  14
4                FC Augsburg   8  14  12
5              VfB Stuttgart  15   8  11
6                 Hamburg SV   8  12  14
7                Hannover 96  12  12  10
8              Hertha Berlin   7  10  17
9           Bayer Leverkusen  15   9  10
10         Borussia Dortmund  25   6   3
11             Bayern Munich  23   4   7
12             VfL Wolfsburg  13   5  16
13                  Nurnberg  12   6  16
14            TSG Hoffenheim  10  11  13
15            Kaiserslautern   4  11  19
16               SC Freiburg  10  10  14
17                     Mainz   9  12  13

In [54]:
r1.to_csv('C:/Users/25160/Desktop/2.csv', index=False)

In [53]:
r1['code']=[i for i in range(18)]

                        name   a   b   c  code
0   Borussia Monchengladbach  17   9   8     0
1                 Schalke 04  20   4  10     1
2                 FC Cologne   8   6  20     2
3              Werder Bremen  11   9  14     3
4                FC Augsburg   8  14  12     4
5              VfB Stuttgart  15   8  11     5
6                 Hamburg SV   8  12  14     6
7                Hannover 96  12  12  10     7
8              Hertha Berlin   7  10  17     8
9           Bayer Leverkusen  15   9  10     9
10         Borussia Dortmund  25   6   3    10
11             Bayern Munich  23   4   7    11
12             VfL Wolfsburg  13   5  16    12
13                  Nurnberg  12   6  16    13
14            TSG Hoffenheim  10  11  13    14
15            Kaiserslautern   4  11  19    15
16               SC Freiburg  10  10  14    16
17                     Mainz   9  12  13    17

In [52]:
[i for i in range(18)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]